# Generated by Django 5.1 on 2024-08-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
