# Generated by Django 5.1 on 2024-08-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_userprofile_delete_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='watchlist',
            field=models.TextField(default='nvda,hood'),
        ),
    ]
